image:
  - Visual Studio 2022

version: 0.1.1-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\hrx.rs

environment:
  matrix:
    - TOOLCHAIN: stable
    - TOOLCHAIN: 1.71.1

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain zip"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu" --default-toolchain="%TOOLCHAIN%"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release

test: off
test_script:
  - cargo test --verbose --release

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
