.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HRX" "1" "August 2019" "hrx.rs developers" ""
.
.SH "NAME"
\fBhrx\fR \- Rust implementation of the HRX plain text archive format
.
.SH "SYNOPSIS"
\fBhrx\fR IN_DIR OUT_DIR \fIOPTIONS\fR
.
.SH "DESCRIPTION"
Rust implementation of the HRX plain text archive format\.
.
.SH "OPTIONS"
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/hrx\.rs/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/hrx\.rs\fR>
